services:

  frontend:
    image: nextjs
    container_name: frontend
    build: ./frontend
    volumes:
    - ./frontend:/app
    - /app/node_modules
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - backend

  backend:
    image: fastify
    container_name: backend
    build: ./backend
    volumes:
    - ./backend:/app
    # - /app/node_modules
    restart: always
    ports:
      - 3030:3030
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/hypertube

  db:
    image: postgres:15
    container_name: hypertube-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hypertube
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
