services:

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend

  frontend:
    image: nextjs
    container_name: frontend
    build: ./frontend
    volumes:
    - ./frontend:/app
    - /app/node_modules
    restart: always
    expose:
      - "3000"
    depends_on:
      - backend
    env_file:
      .env

  backend:
    image: fastify
    container_name: backend
    build: ./backend
    volumes:
    - ./backend:/app
    restart: always
    expose:
      - "3030"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/hypertube 

  db:
    image: postgres:15
    container_name: hypertube-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hypertube
    expose:
      - "5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
